version: '3'
services:
  simple_sports_data_analyzer:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/simple_sports_data_analyzer:0.1
    container_name: analyzer
    environment:
      DB_HOST: allenfield.ddns.net
      DB_PORT: 7306
      DB_USERNAME: allen
      DB_PASSWORD: aldbpw
